# Generated by Django 5.0 on 2023-12-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_rename_nombre_apellido_contacto_nombre_y_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre_y_apellido',
            new_name='nombre_completo',
        ),
    ]
