# Generated by Django 5.0 on 2023-12-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publicado',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imagenes',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tiulo',
            new_name='titulo',
        ),
    ]
